In [1]:
import numpy as np

# 11. How to get the common items between two python numpy arrays?
# Difficulty Level: L2

# Q. Get the common items between a and b

# Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

result = a[np.isin(a, b)]
print(np.unique(result))

# np.intersect1d(a,b)

[2 4]


In [3]:
# 12. How to remove from one array those items that exist in another?
# Difficulty Level: L2

# Q. From array a remove all items present in array b

# Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


In [2]:
# 13. How to get the positions where elements of two arrays match?
# Difficulty Level: L2

# Q. Get the positions where elements of a and b match

# Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

result = [np.where(a==b)]
print(result)

[(array([1, 3, 5, 7], dtype=int64),)]


In [3]:
# 14. How to extract all numbers between a given range from a numpy array?
# Difficulty Level: L2

# Q. Get all items between 5 and 10 from a.

# Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])
a=a[np.where((a>=5) & (a<=10))]
print(a)

# index = np.where(np.logical_and(a>=5, a<=10))

[ 6  9 10]


In [6]:
# 15. How to make a python function that handles scalars to work on numpy arrays?
# Difficulty Level: L2

# Q. Convert the function maxx that works on two scalars, to work on two arrays.

# Input:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

def pair_maxx(a, b):
    result = [np.where(a>b,a,b)]
    return result

print(pair_maxx(a, b))



[array([6, 7, 9, 8, 9, 7, 5])]


In [11]:
# 16. How to swap two columns in a 2d numpy array?
# Difficulty Level: L2

# Q. Swap columns 1 and 2 in the array arr.
#  나중에 다시 풀어보기

arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [12]:
# 17. How to swap two rows in a 2d numpy array?
# Difficulty Level: L2

# Q. Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [19]:
# 18. How to reverse the rows of a 2D array?
# Difficulty Level: L2

# Q. Reverse the rows of a 2D array arr.

# Input
arr = np.arange(9).reshape(3,3)
arr[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [20]:
# 19. How to reverse the columns of a 2D array?
# Difficulty Level: L2

# Q. Reverse the columns of a 2D array arr.

# Input
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [22]:
# 20. How to create a 2D array containing random floats between 5 and 10?
# Difficulty Level: L2

# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

arr=np.random.uniform(5, 10, size=(5, 3))

arr

array([[8.14391977, 7.26706039, 7.09278705],
       [6.08050377, 7.88083052, 9.5759798 ],
       [5.13021146, 7.7314752 , 7.39128062],
       [6.62008897, 9.81613933, 9.02795339],
       [7.30437215, 6.82772991, 7.63726408]])