In [2]:
import numpy as np

# 21. How to print only 3 decimal places in python numpy array?
# Difficulty Level: L1

# Q. Print or show only 3 decimal places of the numpy array rand_arr.

# Input:

rand_arr = np.random.random((5,3))

result = np.around(rand_arr,3)
print(result)

# np.set_printoptions(precision=3)

[[0.841 0.175 0.583]
 [0.039 0.993 0.181]
 [0.82  0.672 0.855]
 [0.926 0.042 0.113]
 [0.761 0.305 0.1  ]]


In [4]:
# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
# Difficulty Level: L1

# Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

# Input:

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True)
rand_arr


array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])

In [8]:
# 23. How to limit the number of items printed in output of numpy array?
# Difficulty Level: L1

# Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

# Input:

a = np.arange(15)
np.set_printoptions(threshold=6)
a




array([ 0,  1,  2, ..., 12, 13, 14])

In [11]:
# 24. How to print the full numpy array without truncating
# Difficulty Level: L1

# Q. Print the full numpy array a without truncating.

# Input:

np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold=np.inf)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
# 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
# Difficulty Level: L2

# Q. Import the iris dataset keeping the text intact.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


In [24]:
# 26. How to extract a particular column from 1D array of tuples?
# Difficulty Level: L2
# 나중에 다시 풀기

# Q. Extract the text column species from the 1D iris imported in previous question.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

species = np.array([row[4] for row in iris_1d])
species

C:\Users\BIT\anaconda3\envs\data-anal-env\lib\site-packages\ipykernel_launcher.py:7: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  import sys


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',
       b'Iris-versicol

In [39]:
# 27. How to convert a 1d array of tuples to a 2d numpy array?
# Difficulty Level: L2

# Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.
# 나중에 다시

# Input:
result = np.array([row.tolist()[:4] for row in iris_1d])
result


[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
# 28. How to compute the mean, median, standard deviation of a numpy array?
# Difficulty: L1

# Q. Find the mean, median, standard deviation of iris's sepallength (1st column)

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([row[0] for row in iris_1d])


In [51]:
import numpy as np

def solution(bridge_length, weight, truck_weights):
    answer = 0
    
    # 대기 트럭 리스트
    truck_list = truck_weights
    
    # 도착한 트럭들
    arr_truck_list = []
    
    
    # 운전하고 있는 트럭들
    driving_truck_list = []
    
    
    # 타임 리스트 생성
    # 각 트럭마다 경과 시간을 저장해야 한다.
    time_list = np.array([1])
    
    # 첫 트럭은 어떠한 조건이든 무조건 출발 가능
    driving_truck_list.append(truck_list.pop(0))
    
    # 전체 걸리는 시간 변수 필요
    time=1
    
    while len(truck_list)!=0:
        
        # 시간은 계속 증가
        time+=1
        
        
        if sum(driving_truck_list)+truck_list[0]<=weight:
            driving_truck_list.append(truck_list.pop(0))

            # 모든 트럭들의 경과시간을 1씩 더하고 새로운 트럭을 추가한다.
            time_list+=1
            time_list = np.append(time_list, np.array([1]))
            print(driving_truck_list)

        else:
            # 모든 트럭들의 경과시간을 1씩 더한다.
            time_list+=1

        
        # 건너는 시간과 다리 길이가 같으면 트럭은 운전을 완료한다.        
        if time_list[0]==bridge_length:
            arr_truck_list.append(driving_truck_list.pop(0))
            time_list = np.delete(time_list, 0)
            
        else:
            pass
        
    # 트럭이 전부 도착하지 않았으면 계속 수행해야 함    
    while len(driving_truck_list)!=0:
        # 시간은 계속 증가
        time+=1
        
        time_list+=1
        
        if time_list[0]==bridge_length:
            arr_truck_list.append(driving_truck_list.pop(0))
            time_list = np.delete(time_list, 0)
            
        else:
            pass
        
        
    answer = time
    
    return answer

print(solution(2,10,[7,4,5,6]))


[4]
[4, 5]
[6]
7
