In [2]:
# 1. Import numpy as np and see the version
import numpy as np

In [4]:
# 2. How to create a 1D array?
print(np.array(range(10)))

[0 1 2 3 4 5 6 7 8 9]


In [5]:
# 3. How to create a boolean array?
#Create a 3×3 numpy array of all True’s

arr = np.full(9, True).reshape(3,3)
print(arr)



[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [6]:
# 4. How to extract items that satisfy a given condition from 1D array?
# Q. Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

new_arr = np.where(arr%2==1)
print(new_arr)

(array([1, 3, 5, 7, 9], dtype=int64),)


In [7]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
# Difficulty Level: L1

# Q. Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.where(arr%2==1,-arr,arr)
print(arr)

[ 0 -1  2 -3  4 -5  6 -7  8 -9]


In [8]:
# 6. How to replace items that satisfy a condition without affecting the original array?
# Difficulty Level: L2

# Q. Replace all odd numbers in arr with -1 without changing arr


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

out = np.where(arr%2==1,-arr,arr)
print(out)
print(arr)

[ 0 -1  2 -3  4 -5  6 -7  8 -9]
[0 1 2 3 4 5 6 7 8 9]


In [13]:
# 7. How to reshape an array?
# Difficulty Level: L1

# Q. Convert a 1D array to a 2D array with 2 rows

# Input:


arr = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr.reshape(2,5)
print(arr)

arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols



[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
# 8. How to stack two arrays vertically?
# Difficulty Level: L2

# Q. Stack arrays a and b vertically


a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

result = np.concatenate((a, b), axis=0)

print(result)

# Method 2:
# np.vstack([a, b])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [4]:
# 9. How to stack two arrays horizontally?
# Difficulty Level: L2

# Q. Stack the arrays a and b horizontally.


a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

result = np.concatenate((a, b), axis=1)
print(result)

new_result = np.hstack([a, b])
print(new_result)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [10]:
# 10. How to generate custom sequences in numpy without hardcoding?
# Difficulty Level: L2

# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.



a = np.array([1,2,3])

rep1 = np.repeat(a.tolist(),3)
rep2 = np.array(a.tolist()*3)

result = np.hstack([rep1, rep2])
print(result)



[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
