In [1]:
import cv2

In [2]:
import numpy as np

In [3]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np 

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import optimizers, initializers, regularizers, metrics

In [4]:
import os

In [5]:
path = 'C:/image/training/tower1'
train_image1 = os.listdir(path)
train_list1_py = [file for file in train_image1 if file.endswith('.jpg')] #

In [6]:
train_list1_py

['graytower_num1.jpg',
 'graytower_num10.jpg',
 'graytower_num11.jpg',
 'graytower_num12.jpg',
 'graytower_num13.jpg',
 'graytower_num14.jpg',
 'graytower_num15.jpg',
 'graytower_num16.jpg',
 'graytower_num17.jpg',
 'graytower_num18.jpg',
 'graytower_num19.jpg',
 'graytower_num2.jpg',
 'graytower_num20.jpg',
 'graytower_num21.jpg',
 'graytower_num22.jpg',
 'graytower_num23.jpg',
 'graytower_num24.jpg',
 'graytower_num25.jpg',
 'graytower_num26.jpg',
 'graytower_num27.jpg',
 'graytower_num28.jpg',
 'graytower_num29.jpg',
 'graytower_num3.jpg',
 'graytower_num30.jpg',
 'graytower_num31.jpg',
 'graytower_num32.jpg',
 'graytower_num33.jpg',
 'graytower_num34.jpg',
 'graytower_num35.jpg',
 'graytower_num36.jpg',
 'graytower_num37.jpg',
 'graytower_num38.jpg',
 'graytower_num39.jpg',
 'graytower_num4.jpg',
 'graytower_num40.jpg',
 'graytower_num41.jpg',
 'graytower_num42.jpg',
 'graytower_num43.jpg',
 'graytower_num44.jpg',
 'graytower_num45.jpg',
 'graytower_num46.jpg',
 'graytower_num47.jp

In [7]:
real_image1 = [cv2.imread("C:/image/training/tower1/" + x, cv2.IMREAD_GRAYSCALE) for x in train_list1_py]
real_image1

[array([[ 43,  43,  43, ..., 100, 100, 100],
        [ 43,  43,  43, ..., 100, 101, 101],
        [ 43,  43,  43, ..., 100, 101, 101],
        ...,
        [ 48,  57,  48, ...,  13,  14,  14],
        [ 48,  57,  46, ...,  13,  13,  13],
        [ 53,  60,  46, ...,  12,  13,  13]], dtype=uint8),
 array([[24, 23, 23, ..., 27, 28, 28],
        [24, 23, 23, ..., 27, 28, 28],
        [23, 24, 24, ..., 27, 27, 27],
        ...,
        [ 4,  3, 22, ...,  3,  6,  9],
        [ 9,  6, 17, ...,  8,  7,  6],
        [ 5,  5, 11, ...,  7,  6,  6]], dtype=uint8),
 array([[ 22,  23,  23, ...,  60,  59,  59],
        [ 22,  22,  22, ...,  59,  59,  59],
        [ 22,  22,  22, ...,  58,  59,  60],
        ...,
        [  4,   4,   4, ...,  88,  30,  15],
        [  4,   4,   4, ..., 111,  62,  16],
        [  4,   5,   5, ...,  98, 107,  19]], dtype=uint8),
 array([[23, 23, 22, ..., 28, 29, 29],
        [23, 23, 23, ..., 28, 29, 29],
        [23, 23, 23, ..., 28, 28, 29],
        ...,
        [46,

In [8]:
len(real_image1)

91

In [9]:
path2 = 'C:/image/training/tower2'
train_image2 = os.listdir(path2)
train_list2_py = [file for file in train_image2 if file.endswith('.jpg')] #

In [10]:
train_list2_py

['grayanother_tower_num1.jpg',
 'grayanother_tower_num10.jpg',
 'grayanother_tower_num11.jpg',
 'grayanother_tower_num12.jpg',
 'grayanother_tower_num13.jpg',
 'grayanother_tower_num14.jpg',
 'grayanother_tower_num15.jpg',
 'grayanother_tower_num16.jpg',
 'grayanother_tower_num17.jpg',
 'grayanother_tower_num18.jpg',
 'grayanother_tower_num19.jpg',
 'grayanother_tower_num2.jpg',
 'grayanother_tower_num20.jpg',
 'grayanother_tower_num21.jpg',
 'grayanother_tower_num22.jpg',
 'grayanother_tower_num23.jpg',
 'grayanother_tower_num24.jpg',
 'grayanother_tower_num25.jpg',
 'grayanother_tower_num26.jpg',
 'grayanother_tower_num27.jpg',
 'grayanother_tower_num28.jpg',
 'grayanother_tower_num29.jpg',
 'grayanother_tower_num3.jpg',
 'grayanother_tower_num30.jpg',
 'grayanother_tower_num31.jpg',
 'grayanother_tower_num32.jpg',
 'grayanother_tower_num33.jpg',
 'grayanother_tower_num34.jpg',
 'grayanother_tower_num35.jpg',
 'grayanother_tower_num36.jpg',
 'grayanother_tower_num37.jpg',
 'grayanoth

In [11]:
real_image2 = [cv2.imread("C:/image/training/tower2/" + x,cv2.IMREAD_GRAYSCALE) for x in train_list2_py]
real_image2

[array([[107, 109, 111, ..., 122, 122, 121],
        [109, 111, 113, ..., 124, 123, 122],
        [112, 113, 115, ..., 124, 123, 122],
        ...,
        [ 12,  11,   9, ...,  10,  12,  13],
        [ 11,  10,   9, ...,   9,  10,  11],
        [  8,   8,   8, ...,   9,  10,   9]], dtype=uint8),
 array([[138, 139, 140, ..., 126, 125, 124],
        [140, 141, 142, ..., 126, 125, 124],
        [142, 143, 144, ..., 127, 126, 125],
        ...,
        [ 42,  38,  30, ...,   6,   6,   6],
        [ 38,  34,  28, ...,   5,   5,   6],
        [ 35,  31,  25, ...,   5,   5,   5]], dtype=uint8),
 array([[141, 141, 141, ..., 133, 133, 133],
        [141, 141, 141, ..., 133, 133, 133],
        [141, 141, 141, ..., 133, 133, 133],
        ...,
        [ 15,  15,  14, ...,  27,  25,  21],
        [ 14,  15,  14, ...,  27,  27,  23],
        [ 13,  14,  14, ...,  24,  26,  22]], dtype=uint8),
 array([[145, 146, 148, ..., 121, 120, 119],
        [147, 148, 149, ..., 122, 121, 120],
        [149, 15

In [12]:
len(real_image2)

78

In [13]:
for i in range(len(real_image1)):    
    dst = cv2.resize(real_image1[i], dsize=(400, 600), interpolation=cv2.INTER_AREA)
    cv2.imwrite('C:/image/training/tower1/gray' + 'tower_num' + str(i+1) + '.jpg', dst)


    

In [14]:
for i in range(len(real_image2)):    
    dst = cv2.resize(real_image2[i], dsize=(400, 600), interpolation=cv2.INTER_AREA)
    cv2.imwrite('C:/image/training/tower2/gray' + 'another_tower_num' + str(i+1) + '.jpg', dst)

In [15]:
path3 = 'C:/image/test/tower1'
test_image1 = os.listdir(path3)
train_list3_py = [file for file in test_image1 if file.endswith('.jpg')] #

real_image3 = [cv2.imread("C:/image/test/tower1/" + x,cv2.IMREAD_GRAYSCALE) for x in train_list3_py]
real_image3



[array([[ 19,  19,  19, ...,  29,  29,  29],
        [ 19,  19,  19, ...,  28,  28,  28],
        [ 19,  19,  19, ...,  28,  28,  28],
        ...,
        [ 33,  61,  99, ..., 150, 154, 150],
        [ 45,  36,  89, ..., 154, 156, 148],
        [ 47,  51, 111, ..., 148, 152, 155]], dtype=uint8),
 array([[ 22,  22,  22, ...,  40,  40,  40],
        [ 22,  22,  22, ...,  39,  39,  39],
        [ 22,  22,  22, ...,  39,  39,  39],
        ...,
        [ 40,  40,  37, ..., 160, 158, 160],
        [ 35,  39,  41, ..., 169, 162, 158],
        [ 37,  37,  66, ..., 170, 167, 164]], dtype=uint8),
 array([[ 24,  24,  24, ...,  42,  41,  40],
        [ 24,  24,  24, ...,  41,  41,  40],
        [ 24,  24,  24, ...,  40,  40,  41],
        ...,
        [ 78,  62, 110, ...,  35,  36,  37],
        [ 96, 138, 108, ...,  35,  36,  37],
        [110, 130,  63, ...,  32,  33,  34]], dtype=uint8),
 array([[21, 21, 21, ..., 33, 33, 34],
        [21, 21, 21, ..., 33, 33, 34],
        [21, 21, 21, ..., 33

In [16]:
for i in range(len(real_image3)):    
    dst = cv2.resize(real_image3[i], dsize=(400, 600), interpolation=cv2.INTER_AREA)
    cv2.imwrite('C:/image/test/tower1/gray' + 'test1_tower_num' + str(i+1) + '.jpg', dst)

In [17]:
path4 = 'C:/image/test/tower2'
test_image2 = os.listdir(path4)
train_list4_py = [file for file in test_image2 if file.endswith('.jpg')] #

real_image4 = [cv2.imread("C:/image/test/tower2/" + x,cv2.IMREAD_GRAYSCALE) for x in train_list4_py]
real_image4


[array([[174, 174, 175, ..., 137, 136, 135],
        [175, 175, 176, ..., 138, 137, 136],
        [176, 176, 177, ..., 139, 138, 137],
        ...,
        [  6,   7,   9, ...,   9,  14,  15],
        [  6,   7,   9, ...,   7,  12,  14],
        [  6,   7,   9, ...,   5,  13,  18]], dtype=uint8),
 array([[178, 179, 180, ..., 130, 128, 127],
        [178, 179, 179, ..., 130, 128, 127],
        [178, 178, 179, ..., 130, 128, 127],
        ...,
        [165, 164, 166, ...,   4,   2,   3],
        [164, 166, 163, ...,   3,   2,   5],
        [165, 163, 165, ...,   4,   3,   5]], dtype=uint8),
 array([[193, 193, 193, ..., 163, 162, 161],
        [193, 193, 194, ..., 163, 162, 162],
        [194, 194, 194, ..., 163, 163, 163],
        ...,
        [  2,   2,   2, ...,   6,   6,  10],
        [  3,   3,   3, ...,   7,   6,   7],
        [  3,   3,   3, ...,   7,   6,   6]], dtype=uint8),
 array([[146, 147, 149, ..., 121, 119, 118],
        [148, 149, 150, ..., 123, 122, 121],
        [150, 15

In [18]:
for i in range(len(real_image4)):    
    dst = cv2.resize(real_image4[i], dsize=(400, 600), interpolation=cv2.INTER_AREA)
    cv2.imwrite('C:/image/test/tower2/gray' + 'test2_tower_num' + str(i+1) + '.jpg', dst)

In [19]:
b_size = 5
train_datagen = ImageDataGenerator(rescale=1./255, horizontal_flip = True, # 수평 대칭 이미지를 50%확률로 만듬
                                  width_shift_range = 0.1, # 전체 크기의 10% 범위에서 좌우로 이동
                                  height_shift_range = 0.1,
                                  fill_mode = 'nearest')

In [20]:
train_generator = train_datagen.flow_from_directory('C:/image/training/',target_size=(400,600),
                                                    batch_size=b_size, class_mode='binary')

Found 170 images belonging to 2 classes.


In [21]:
test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory('C:/image/test/',target_size=(400,600),
                                                    batch_size=b_size, class_mode='binary')

Found 60 images belonging to 2 classes.


In [22]:
len(train_generator)

34

In [23]:
len(test_generator)

12

In [24]:
model = Sequential()
model.add(Conv2D(24, (3, 3), input_shape=(400,600,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(24, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(48, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(48))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(2))
model.add(Activation('softmax'))

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 398, 598, 24)      672       
_________________________________________________________________
activation (Activation)      (None, 398, 598, 24)      0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 199, 299, 24)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 197, 297, 24)      5208      
_________________________________________________________________
activation_1 (Activation)    (None, 197, 297, 24)      0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 98, 148, 24)       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 96, 146, 48)       1

In [26]:
# model.compile(loss='sparse_categorical_crossentropy',optimizer=optimizers.Adam(learning_rate=0.0002),\
#               metrics=['accuracy'])

In [27]:
# steps_train = len(train_generator)
# steps_test = len(test_generator)

In [28]:
# history = model.fit(
#        train_generator,
#        steps_per_epoch=steps_train,
#        epochs=20,
#        validation_data=test_generator,
#        validation_steps=steps_test )

In [29]:
# acc = history.history['accuracy']
# val_acc = history.history['val_accuracy']
# y_vloss = history.history['val_loss']
# y_loss = history.history['loss']

# x_len = np.arange(len(y_loss))
# plt.plot(x_len, acc, marker='.', c='cornflowerblue', label='Trainset_acc')
# plt.plot(x_len, val_acc, marker='.', c='blue', label='Testset_acc')
# plt.plot(x_len, y_vloss, marker='.', c='red', label='Testset_loss')
# plt.plot(x_len, y_loss, marker='.', c='lightcoral', label='Trainset_loss')

# plt.legend(loc='upper left')
# plt.grid()
# plt.xlabel('epoch')
# plt.ylabel('loss/acc')
# plt.show()

In [30]:
import cv2, sys
import matplotlib.pyplot as plt
import numpy as np

image_snake = cv2.imread("C:/image/training/tower1/snake.jpg", cv2.IMREAD_UNCHANGED)
image_gray_snake = cv2.imread("C:/image/training/tower1/snake.jpg", cv2.IMREAD_GRAYSCALE)
# cv2.imshow('image', image)
# cv2.imshow('image_gray', image_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()
blur = cv2.GaussianBlur(image_gray_snake, ksize=(5,5), sigmaX=0)
ret, thresh1 = cv2.threshold(blur, 100, 255, cv2.THRESH_BINARY)
edged = cv2.Canny(blur, 100, 250)
cv2.waitKey(0)
# cv2.imshow('closed', closed)
cv2.waitKey(0)
contours, hierarchy = cv2.findContours(edged,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
# 외곽선 그리는 용도. 이미지에 그리기 때문에 이 코드 적용하면 원래 이미지에
# 초록색 선 생김

for cnt in contours:
    area = cv2.contourArea(cnt)
    cv2.drawContours(image_snake,cnt, -1, (0,255,0), 2)
    
cv2.imshow('insect_contour', image_snake)
cv2.waitKey(0)
cv2.destroyAllWindows()



In [58]:
image_insect = cv2.imread("C:/opencv_practice/insects.jpg", cv2.IMREAD_UNCHANGED)
image_gray_insect = cv2.imread("C:/opencv_practice/insects.jpg", cv2.IMREAD_GRAYSCALE)

In [59]:
image_insect

array([[[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       ...,

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]]

In [60]:
cv2.imshow('image', image_insect)
cv2.imshow('image_gray', image_gray_insect)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [34]:
image_insect[17]

array([[247, 247, 247],
       [247, 247, 247],
       [247, 247, 247],
       ...,
       [247, 247, 247],
       [247, 247, 247],
       [247, 247, 247]], dtype=uint8)

In [35]:
insect_blur = cv2.GaussianBlur(image_gray_insect, ksize=(5,5), sigmaX=1)

In [36]:
cv2.imshow('image_blur', insect_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [37]:
insect_edged = cv2.Canny(insect_blur, 10, 250)

In [38]:
cv2.imshow('image_canny', insect_edged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:
insect_contour = image_insect.copy()

In [40]:
contours, hierarchy = cv2.findContours(insect_edged,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE )

In [41]:
contours

[array([[[389, 571]],
 
        [[390, 571]],
 
        [[391, 572]],
 
        [[392, 572]],
 
        [[393, 573]],
 
        [[394, 574]],
 
        [[395, 575]],
 
        [[394, 576]],
 
        [[393, 576]],
 
        [[392, 577]],
 
        [[391, 577]],
 
        [[390, 576]],
 
        [[389, 576]],
 
        [[388, 576]],
 
        [[387, 575]],
 
        [[386, 575]],
 
        [[385, 575]],
 
        [[384, 575]],
 
        [[383, 574]],
 
        [[382, 575]],
 
        [[382, 576]],
 
        [[382, 577]],
 
        [[382, 578]],
 
        [[382, 579]],
 
        [[382, 580]],
 
        [[382, 581]],
 
        [[382, 582]],
 
        [[382, 583]],
 
        [[382, 584]],
 
        [[382, 585]],
 
        [[381, 586]],
 
        [[380, 587]],
 
        [[379, 587]],
 
        [[378, 587]],
 
        [[377, 586]],
 
        [[376, 585]],
 
        [[376, 584]],
 
        [[376, 583]],
 
        [[376, 582]],
 
        [[376, 581]],
 
        [[376, 580]],
 
        [[376, 5

In [42]:
len(contours)

222

In [43]:
for cnt in contours:
    area = cv2.contourArea(cnt)
    cv2.drawContours(insect_contour, cnt, -1, (0,255,0), 2)
    
cv2.imshow('insect_contour', insect_contour)
cv2.waitKey(0)
cv2.destroyAllWindows()
    
    

In [61]:
import cv2, sys
import matplotlib.pyplot as plt
import numpy as np

image_mantis = cv2.imread("C:/opencv_practice/mantis.jpg", cv2.IMREAD_UNCHANGED)
image_gray_mantis = cv2.imread("C:/opencv_practice/mantis.jpg", cv2.IMREAD_GRAYSCALE)

image_mantis = cv2.resize(image_mantis, dsize=(640, 480), interpolation=cv2.INTER_AREA)
image_gray_mantis = cv2.resize(image_gray_mantis, dsize=(640, 480), interpolation=cv2.INTER_AREA)

cv2.imshow('image', image_mantis)
cv2.imshow('image_gray', image_gray_mantis)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [45]:
blur_mantis = cv2.GaussianBlur(image_gray_mantis, ksize=(11,11), sigmaX=5)
cv2.imshow('blur_mantis', blur_mantis)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [46]:
ret, thresh1 = cv2.threshold(blur_mantis, 80, 255, cv2.THRESH_BINARY)

cv2.imshow('thresh1', thresh1)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [47]:
edged_mantis = cv2.Canny(thresh1, 10, 250)
cv2.imshow('edged_mantis', edged_mantis)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [48]:
contour_mantis = image_mantis.copy()

In [49]:
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (7,7))
closed_mantis = cv2.morphologyEx(edged_mantis, cv2.MORPH_CLOSE, kernel)
cv2.imshow('closed_mantis', closed_mantis)
cv2.waitKey(0)

-1

In [50]:
contours, hierarchy = cv2.findContours(closed_mantis,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
# 외곽선 그리는 용도. 이미지에 그리기 때문에 이 코드 적용하면 원래 이미지에
# 초록색 선 생김

for cnt in contours:
    area = cv2.drawContours(contour_mantis, cnt, -1, (0,255,0), 3)
    
    
cv2.imshow('final_result', area)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [51]:
print(len(contours))

6


In [52]:
rea = cv2.drawContours(contour_mantis, contours[3], -1, (0,255,0), 3)
cv2.imshow('final_result', area)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [53]:
contours_xy = np.array(contours)
contours_xy.shape

C:\Users\jinsu\anaconda3\envs\project-env\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


(6,)

In [54]:
contours_xy[1]

array([[[181, 403]],

       [[180, 404]],

       [[179, 404]],

       ...,

       [[184, 404]],

       [[183, 404]],

       [[182, 403]]], dtype=int32)

In [55]:
x_min, x_max = 0,0
value = list()
for i in range(len(contours_xy)):
    for j in range(len(contours_xy[i])):
        value.append(contours_xy[i][j][0][0]) #네번째 괄호가 0일때 x의 값
x_min = min(value)
x_max = max(value)
print(x_min)
print(x_max)
 
# y의 min과 max 찾기
y_min, y_max = 0,0
value = list()
for i in range(len(contours_xy)):
    for j in range(len(contours_xy[i])):
        value.append(contours_xy[i][j][0][1]) #네번째 괄호가 0일때 x의 값
y_min = min(value)
y_max = max(value)
print(y_min)
print(y_max)


0
639
130
444


In [56]:
x = x_min
y = y_min
w = x_max-x_min
h = y_max-y_min

In [57]:
img_trim = image_mantis[y:y+h, x:x+w]
cv2.imwrite('C:/opencv_practice/org_trim.jpg', img_trim)
org_image = cv2.imread('C:/opencv_practice/org_trim.jpg')

cv2.imshow('org_image', img_trim)
cv2.waitKey(0)
cv2.destroyAllWindows()